In [5]:
import pandas as pd

csv_files = [
    '100_epochs_accuracies.csv',
    '300_epochs_accuracies.csv',
    '500_epochs_accuracies.csv',
    '700_epochs_accuracies.csv',
    '700_epochs_accuracies.csv'
]

dataframes = [pd.read_csv(file).drop(columns=['Unnamed: 0'], errors='ignore') for file in csv_files]

combined_accuracies_dataframe = pd.concat(dataframes, ignore_index=True)

combined_accuracies_dataframe = combined_accuracies_dataframe.round(3)
combined_accuracies_dataframe

,Model,Train_Accuracy_Arc,Train_Accuracy_Brc,Train_Accuracy_Token,Val_Accuracy_Arc,Val_Accuracy_Brc,Val_Accuracy_Token,Test_Accuracy_Arc,Test_Accuracy_Brc,Test_Accuracy_Token
0,100 epochs,0.958,0.917,0.974,0.919,0.827,0.942,0.921,0.826,0.945
1,300 epochs,0.980,0.964,0.992,0.919,0.828,0.953,0.920,0.824,0.955
2,500 epochs,0.985,0.974,0.994,0.917,0.827,0.955,0.920,0.827,0.956
3,700 epochs,0.990,0.981,0.996,0.920,0.826,0.957,0.923,0.829,0.958
4,700 epochs,0.990,0.981,0.996,0.920,0.826,0.957,0.923,0.829,0.958

In [2]:
import pandas as pd

test_files = [
    'output_100_epochs_test_data.txt', 'output_300_epochs_test_data.txt',
    'output_500_epochs_test_data.txt', 'output_700_epochs_test_data.txt', 
    'output_1000_epochs_test_data.txt'
]
train_files = [
    'output_100_epochs_train_data.txt', 'output_300_epochs_train_data.txt',
    'output_500_epochs_train_data.txt', 'output_700_epochs_train_data.txt',
    'output_1000_epochs_train_data.txt'
]
val_files = [
    'output_100_epochs_val_data.txt', 'output_300_epochs_val_data.txt',
    'output_500_epochs_val_data.txt', 'output_700_epochs_val_data.txt',
    'output_1000_epochs_val_data.txt'
]

data_train = {'Model': [], 'Top-1 Train': [], 'Top-3 Train': [], 'Top-5 Train': [], 'Top-10 Train': []}
data_val = {'Model': [], 'Top-1 Val': [], 'Top-3 Val': [], 'Top-5 Val': [], 'Top-10 Val': []}
data_test = {'Model': [], 'Top-1 Test': [], 'Top-3 Test': [], 'Top-5 Test': [], 'Top-10 Test': []}

def extract_top_values(file_path):
    top_values = {'Top-1': None, 'Top-3': None, 'Top-5': None, 'Top-10': None}
    with open(file_path, 'r') as file:
        for line in file:
            for key in top_values.keys():
                if key in line:
                    parts = line.split(':')
                    if len(parts) == 2:
                        metric = parts[0].strip()
                        value = parts[1].strip()
            
                        try:
                            value = float(value)
                        except ValueError:
                            value = None
                        
                        if metric in top_values:
                            top_values[metric] = value
    return top_values

for train_file, val_file, test_file in zip(train_files, val_files, test_files):
    epochs = train_file.split('_')[1]
    
    train_values = extract_top_values(train_file)
    val_values = extract_top_values(val_file)
    test_values = extract_top_values(test_file)
    
    data_train['Model'].append(f"{epochs} epochs")
    data_val['Model'].append(f"{epochs} epochs")
    data_test['Model'].append(f"{epochs} epochs")
    
    for key in ['Top-1', 'Top-3', 'Top-5', 'Top-10']:
        data_train[f'{key} Train'].append(round(train_values[key],3))
        data_val[f'{key} Val'].append(round(val_values[key],3))
        data_test[f'{key} Test'].append(round(test_values[key],3))

df_train = pd.DataFrame(data_train)
df_val = pd.DataFrame(data_val)
df_test = pd.DataFrame(data_test)

In [11]:
df_train

         Model  Top-1 Train  Top-3 Train  Top-5 Train  Top-10 Train
0   100 epochs        0.271        0.407        0.468         0.527
1   300 epochs        0.619        0.749        0.774         0.787
2   500 epochs        0.669        0.776        0.789         0.797
3   700 epochs        0.715        0.788        0.796         0.800
4  1000 epochs        0.716        0.790        0.795         0.801

In [12]:
df_val

         Model  Top-1 Val  Top-3 Val  Top-5 Val  Top-10 Val
0   100 epochs      0.107      0.180      0.213       0.250
1   300 epochs      0.178      0.267      0.315       0.361
2   500 epochs      0.183      0.272      0.309       0.356
3   700 epochs      0.196      0.287      0.322       0.364
4  1000 epochs      0.188      0.291      0.325       0.371

In [13]:
df_test

         Model  Top-1 Test  Top-3 Test  Top-5 Test  Top-10 Test
0   100 epochs       0.117       0.195       0.237        0.275
1   300 epochs       0.161       0.262       0.301        0.365
2   500 epochs       0.180       0.288       0.325        0.375
3   700 epochs       0.191       0.298       0.340        0.383
4  1000 epochs       0.185       0.295       0.341        0.382

In [14]:
import pandas as pd

accuracy_csv_file_biochem = '1000_epochs_biochem_accuracies.csv'

accuracy_df_biochem = pd.read_csv(accuracy_csv_file_biochem).drop(columns=['Unnamed: 0'], errors='ignore')
accuracy_df_biochem = accuracy_df_biochem.round(3)

lowerLR_accuracy_csv_file_biochem = '1000_epochs_biochem_10times_lowerLR_accuracies.csv'

lowerLR_accuracy_df_biochem = pd.read_csv(lowerLR_accuracy_csv_file_biochem).drop(columns=['Unnamed: 0'], errors='ignore')
lowerLR_accuracy_df_biochem = lowerLR_accuracy_df_biochem.round(3)

_9layers_accuracy_csv_file_biochem_1000 = '1000_epochs_biochem_9layers_accuracies.csv'

_9layers_accuracy_df_biochem_1000 = pd.read_csv(_9layers_accuracy_csv_file_biochem_1000).drop(columns=['Unnamed: 0'], errors='ignore')
_9layers_accuracy_df_biochem_1000 = _9layers_accuracy_df_biochem_1000.round(3)

In [15]:
acurracies_df = pd.concat([combined_accuracies_dataframe, accuracy_df_biochem], ignore_index=True)
acurracies_df = pd.concat([acurracies_df, lowerLR_accuracy_df_biochem], ignore_index=True)
acurracies_df = pd.concat([acurracies_df, _9layers_accuracy_df_biochem_1000], ignore_index=True)
acurracies_df

,Model,Train_Accuracy_Arc,Train_Accuracy_Brc,Train_Accuracy_Token,Val_Accuracy_Arc,Val_Accuracy_Brc,Val_Accuracy_Token,Test_Accuracy_Arc,Test_Accuracy_Brc,Test_Accuracy_Token
0,100 epochs,0.958,0.917,0.974,0.919,0.827,0.942,0.921,0.826,0.945
1,300 epochs,0.980,0.964,0.992,0.919,0.828,0.953,0.920,0.824,0.955
2,500 epochs,0.985,0.974,0.994,0.917,0.827,0.955,0.920,0.827,0.956
3,700 epochs,0.990,0.981,0.996,0.920,0.826,0.957,0.923,0.829,0.958
4,700 epochs,0.990,0.981,0.996,0.920,0.826,0.957,0.923,0.829,0.958
5,1000 epochs biochem,0.993,0.988,0.998,0.922,0.832,0.973,0.927,0.837,0.975
6,1000 epochs biochem lowerLR,0.974,0.959,0.994,0.922,0.835,0.977,0.926,0.837,0.979
7,1000 epochs biochem 9layers,0.956,0.938,0.991,0.921,0.834,0.973,0.926,0.837,0.976

In [16]:
import pandas as pd
import re

test_files_biochem = [
    'output_1000_epochs_biochem_test_data.txt', 
    'output_1000_epochs_biochem_10times_lowerLR_test_data.txt',
    'output_1000_epochs_biochem_9layers_test_data.txt'
]
train_files_biochem = [
    'output_1000_epochs_biochem_train_data.txt',
    'output_1000_epochs_biochem_10times_lowerLR_train_data.txt',
    'output_1000_epochs_biochem_9layers_train_data.txt'
]
val_files_biochem = [
    'output_1000_epochs_biochem_val_data.txt',
    'output_1000_epochs_biochem_10times_lowerLR_val_data.txt',
    'output_1000_epochs_biochem_9layers_val_data.txt'
]

data_train_biochem = {'Model': [], 'Top-1 Train': [], 'Top-3 Train': [], 'Top-5 Train': [], 'Top-10 Train': []}
data_val_biochem = {'Model': [], 'Top-1 Val': [], 'Top-3 Val': [], 'Top-5 Val': [], 'Top-10 Val': []}
data_test_biochem = {'Model': [], 'Top-1 Test': [], 'Top-3 Test': [], 'Top-5 Test': [], 'Top-10 Test': []}

for train_file_biochem, val_file_biochem, test_file_biochem in zip(train_files_biochem, val_files_biochem, test_files_biochem):
    
    if '10times_lowerLR' in train_file_biochem and val_file_biochem and test_file_biochem:
        model_name = '1000 epochs biochem 10times lowerLR'
    elif '9layers' in train_file_biochem and val_file_biochem and test_file_biochem:
        model_name = '1000 epochs biochem 9layers'
    else:
        model_name = '1000 epochs biochem'
    
    train_values = extract_top_values(train_file_biochem)
    val_values = extract_top_values(val_file_biochem)
    test_values = extract_top_values(test_file_biochem)
    
    data_train_biochem['Model'].append(model_name)
    data_val_biochem['Model'].append(model_name)
    data_test_biochem['Model'].append(model_name)
    
    for key in ['Top-1', 'Top-3', 'Top-5', 'Top-10']:
        data_train_biochem[f'{key} Train'].append(round(train_values[key],3))
        data_val_biochem[f'{key} Val'].append(round(val_values[key],3))
        data_test_biochem[f'{key} Test'].append(round(test_values[key],3))

df_train_biochem = pd.DataFrame(data_train_biochem)
df_val_biochem = pd.DataFrame(data_val_biochem)
df_test_biochem = pd.DataFrame(data_test_biochem)

In [17]:
df_train_biochem

,Model,Top-1 Train,Top-3 Train,Top-5 Train,Top-10 Train
0,1000 epochs biochem,0.793,0.836,0.842,0.845
1,1000 epochs biochem lowerLR,0.673,0.781,0.803,0.826
2,1000 epochs biochem 9layers,0.569,0.727,0.761,0.795

In [18]:
df_test_biochem

,Model,Top-1 Test,Top-3 Test,Top-5 Test,Top-10 Test
0,1000 epochs biochem,0.299,0.414,0.440,0.484
1,1000 epochs biochem lowerLR,0.321,0.450,0.492,0.552
2,1000 epochs biochem 9layers,0.274,0.423,0.470,0.531

In [19]:
df_val_biochem

                         Model  Top-1 Val  Top-3 Val  Top-5 Val  Top-10 Val
0          1000 epochs biochem      0.290      0.398      0.440       0.483
1  1000 epochs biochem lowerLR      0.298      0.415      0.453       0.509
2  1000 epochs biochem 9layers      0.263      0.389      0.442       0.512

In [1]:
import pandas as pd

accuracy_csv_file_700 = '700_epochs_accuracies.csv'

accuracy_df_700 = pd.read_csv(accuracy_csv_file_700).drop(columns=['Unnamed: 0'], errors='ignore')
accuracy_df_700 = accuracy_df_700.round(3)

accuracy_csv_file_biochem_700 = '700_epochs_biochem_accuracies.csv'

accuracy_df_biochem_700 = pd.read_csv(accuracy_csv_file_biochem_700).drop(columns=['Unnamed: 0'], errors='ignore')
accuracy_df_biochem_700 = accuracy_df_biochem_700.round(3)

lowerLR_accuracy_csv_file_biochem_700 = '700_epochs_biochem_10times_lowerLR_accuracies.csv'

lowerLR_accuracy_df_biochem_700 = pd.read_csv(lowerLR_accuracy_csv_file_biochem_700).drop(columns=['Unnamed: 0'], errors='ignore')
lowerLR_accuracy_df_biochem_700 = lowerLR_accuracy_df_biochem_700.round(3)

lowerLR_SMO_accuracy_csv_file_biochem_700 = '700_epochs_biochem_SMO_10times_lowerLR_accuracies.csv'

lowerLR_SMO_accuracy_df_biochem_700 = pd.read_csv(lowerLR_SMO_accuracy_csv_file_biochem_700).drop(columns=['Unnamed: 0'], errors='ignore')
lowerLR_SMO_accuracy_df_biochem_700 = lowerLR_SMO_accuracy_df_biochem_700.round(3)

_9layers_accuracy_csv_file_biochem_700 = '700_epochs_biochem_9layers_accuracies.csv'

_9layers_accuracy_df_biochem_700 = pd.read_csv(_9layers_accuracy_csv_file_biochem_700).drop(columns=['Unnamed: 0'], errors='ignore')
_9layers_accuracy_df_biochem_700 = _9layers_accuracy_df_biochem_700.round(3)

In [2]:
accuracy_df_700 = pd.concat([accuracy_df_700, accuracy_df_biochem_700], ignore_index=True)
accuracy_df_700 = pd.concat([accuracy_df_700, lowerLR_accuracy_df_biochem_700], ignore_index=True)
accuracy_df_700 = pd.concat([accuracy_df_700, lowerLR_SMO_accuracy_df_biochem_700], ignore_index=True)
accuracy_df_700 = pd.concat([accuracy_df_700, _9layers_accuracy_df_biochem_700], ignore_index=True)
accuracy_df_700

,Model,Train_Accuracy_Arc,Train_Accuracy_Brc,Train_Accuracy_Token,Val_Accuracy_Arc,Val_Accuracy_Brc,Val_Accuracy_Token,Test_Accuracy_Arc,Test_Accuracy_Brc,Test_Accuracy_Token
0,700 epochs,0.990,0.981,0.996,0.920,0.826,0.957,0.923,0.829,0.958
1,700 epochs biochem,0.992,0.986,0.997,0.922,0.833,0.974,0.927,0.838,0.976
2,700 epochs biochem lowerLR,0.967,0.945,0.992,0.922,0.837,0.976,0.925,0.838,0.978
3,700 epochs biochem SMO 10times lowerLR,0.952,0.908,0.988,0.939,0.887,0.990,0.947,0.894,0.986
4,700 epochs biochem 9layers,0.953,0.922,0.989,0.921,0.832,0.973,0.924,0.838,0.976

In [22]:
import pandas as pd
import re

test_files_biochem_700 = [
    'output_700_epochs_biochem_test_data.txt', 
    'output_700_epochs_biochem_10times_lowerLR_test_data.txt',
    'output_700_epochs_biochem_9layers_test_data.txt'
]
train_files_biochem_700 = [
    'output_700_epochs_biochem_train_data.txt',
    'output_700_epochs_biochem_10times_lowerLR_train_data.txt',
    'output_700_epochs_biochem_9layers_train_data.txt'
]
val_files_biochem_700 = [
    'output_700_epochs_biochem_val_data.txt',
    'output_700_epochs_biochem_10times_lowerLR_val_data.txt',
    'output_700_epochs_biochem_9layers_val_data.txt'
]

data_train_biochem_700 = {'Model': [], 'Top-1 Train': [], 'Top-3 Train': [], 'Top-5 Train': [], 'Top-10 Train': []}
data_val_biochem_700 = {'Model': [], 'Top-1 Val': [], 'Top-3 Val': [], 'Top-5 Val': [], 'Top-10 Val': []}
data_test_biochem_700 = {'Model': [], 'Top-1 Test': [], 'Top-3 Test': [], 'Top-5 Test': [], 'Top-10 Test': []}

for train_file_biochem_700, val_file_biochem_700, test_file_biochem_700 in zip(train_files_biochem_700, val_files_biochem_700, test_files_biochem_700):
    
    if '10times_lowerLR' in train_file_biochem_700 and val_file_biochem_700 and test_file_biochem_700:
        model_name = '700 epochs biochem 10times lowerLR'
    elif '9layers' in train_file_biochem_700 and val_file_biochem_700 and test_file_biochem_700:
        model_name = '700 epochs biochem 9layers'
    else:
        model_name = '700 epochs biochem'
    
    train_values_700 = extract_top_values(train_file_biochem_700)
    val_values_700 = extract_top_values(val_file_biochem_700)
    test_values_700 = extract_top_values(test_file_biochem_700)
    
    data_train_biochem_700['Model'].append(model_name)
    data_val_biochem_700['Model'].append(model_name)
    data_test_biochem_700['Model'].append(model_name)
    
    for key in ['Top-1', 'Top-3', 'Top-5', 'Top-10']:
        data_train_biochem_700[f'{key} Train'].append(round(train_values_700[key],3))
        data_val_biochem_700[f'{key} Val'].append(round(val_values_700[key],3))
        data_test_biochem_700[f'{key} Test'].append(round(test_values_700[key],3))

df_train_biochem_700 = pd.DataFrame(data_train_biochem_700)
df_val_biochem_700 = pd.DataFrame(data_val_biochem_700)
df_test_biochem_700= pd.DataFrame(data_test_biochem_700)

In [23]:
df_train_biochem_700

,Model,Top-1 Train,Top-3 Train,Top-5 Train,Top-10 Train
0,700 epochs biochem,0.600,0.744,0.778,0.811
1,700 epochs biochem lowerLR,0.600,0.744,0.778,0.811
2,700 epochs biochem 9layers,0.527,0.682,0.725,0.769

In [24]:
df_val_biochem_700

                        Model  Top-1 Val  Top-3 Val  Top-5 Val  Top-10 Val
0          700 epochs biochem      0.304      0.401      0.434       0.485
1  700 epochs biochem lowerLR      0.282      0.417      0.467       0.522
2  700 epochs biochem 9layers      0.266      0.385      0.429       0.490

In [25]:
df_test_biochem_700

                        Model  Top-1 Test  Top-3 Test  Top-5 Test  Top-10 Test
0          700 epochs biochem       0.311       0.419       0.454        0.507
1  700 epochs biochem lowerLR       0.311       0.455       0.491        0.553
2  700 epochs biochem 9layers       0.285       0.410       0.460        0.528

In [1]:
import pandas as pd

accuracy_csv_file_original_biochem = 'original_biochem_accuracies.csv'

accuracy_df_original_biochem = pd.read_csv(accuracy_csv_file_original_biochem).drop(columns=['Unnamed: 0'], errors='ignore')
accuracy_df_original_biochem = accuracy_df_original_biochem.round(3)

accuracy_csv_file_original_biochem_SMO = 'original_biochem_SMO_accuracies.csv'

accuracy_df_original_biochem_SMO = pd.read_csv(accuracy_csv_file_original_biochem_SMO).drop(columns=['Unnamed: 0'], errors='ignore')
accuracy_df_original_biochem_SMO = accuracy_df_original_biochem_SMO.round(3)

In [2]:
accuracy_original_biochem = pd.concat([accuracy_df_original_biochem, accuracy_df_original_biochem_SMO], ignore_index=True)

In [3]:
accuracy_original_biochem

,Model,Train_Accuracy_Arc,Train_Accuracy_Brc,Train_Accuracy_Token,Val_Accuracy_Arc,Val_Accuracy_Brc,Val_Accuracy_Token,Test_Accuracy_Arc,Test_Accuracy_Brc,Test_Accuracy_Token
0,original biochem,0.876,0.741,0.910,0.873,0.742,0.909,0.880,0.749,0.912
1,original biochem SMO,0.873,0.736,0.917,0.863,0.716,0.919,0.858,0.714,0.916

In [6]:
import pandas as pd
import re

test_files_original_biochem = [
    'output_original_biochem_test_data.txt', 
    'output_original_biochem_SMO_test_data.txt']

train_files_original_biochem = [
    'output_original_biochem_train_data.txt',
    'output_original_biochem_SMO_train_data.txt'
]
val_files_original_biochem = [
    'output_original_biochem_val_data.txt',
    'output_original_biochem_SMO_val_data.txt'
]

data_train_original_biochem = {'Model': [], 'Top-1 Train': [], 'Top-3 Train': [], 'Top-5 Train': [], 'Top-10 Train': []}
data_val_original_biochem = {'Model': [], 'Top-1 Val': [], 'Top-3 Val': [], 'Top-5 Val': [], 'Top-10 Val': []}
data_test_original_biochem = {'Model': [], 'Top-1 Test': [], 'Top-3 Test': [], 'Top-5 Test': [], 'Top-10 Test': []}

for test_file_original_biochem, train_file_original_biochem, val_file_original_biochem in zip(test_files_original_biochem, train_files_original_biochem, val_files_original_biochem):
    
    if 'SMO' in test_file_original_biochem and test_file_original_biochem and test_file_original_biochem:
        model_name = 'Original Biochem - SMO'
    else:
        model_name = 'Original Biochem'
    
    train_values_original_biochem = extract_top_values(train_file_original_biochem)
    val_values_original_biochem = extract_top_values(val_file_original_biochem)
    test_values_original_biochem = extract_top_values(test_file_original_biochem)
    
    data_train_original_biochem['Model'].append(model_name)
    data_val_original_biochem['Model'].append(model_name)
    data_test_original_biochem['Model'].append(model_name)
    
    for key in ['Top-1', 'Top-3', 'Top-5', 'Top-10']:
        data_train_original_biochem[f'{key} Train'].append(round(train_values_original_biochem[key],3))
        data_val_original_biochem[f'{key} Val'].append(round(val_values_original_biochem[key],3))
        data_test_original_biochem[f'{key} Test'].append(round(test_values_original_biochem[key],3))

df_train_original_biochem = pd.DataFrame(data_train_original_biochem)
df_val_original_biochem = pd.DataFrame(data_val_original_biochem)
df_test_original_biochem = pd.DataFrame(data_test_original_biochem)

In [7]:
df_train_original_biochem

                    Model  Top-1 Train  Top-3 Train  Top-5 Train  Top-10 Train
0        Original Biochem        0.009        0.020        0.029         0.042
1  Original Biochem - SMO        0.013        0.032        0.041         0.051

In [8]:
df_val_original_biochem

                    Model  Top-1 Val  Top-3 Val  Top-5 Val  Top-10 Val
0        Original Biochem      0.011      0.028      0.037       0.051
1  Original Biochem - SMO      0.011      0.030      0.046       0.057

In [9]:
df_test_original_biochem

                    Model  Top-1 Test  Top-3 Test  Top-5 Test  Top-10 Test
0        Original Biochem       0.011       0.024       0.031        0.051
1  Original Biochem - SMO       0.030       0.046       0.057        0.061

In [15]:
import pandas as pd
import re

test_files_twice = [ 
    'output_700_epochs_biochem_10times_lowerLR_test_data.txt',
    'output_700_epochs_biochem_SMO_10times_lowerLR_test_data.txt',
    'output_700_epochs_biochem_100times_lowerLR_test_data.txt',
    'output_700_epochs_biochem_SMO_100times_lowerLR_test_data.txt',
    'output_700_epochs_biochem_1000times_lowerLR_test_data.txt',
    'output_700_epochs_biochem_SMO_1000times_lowerLR_test_data.txt',
    'output_original_biochem_SMO_test_data.txt'
]
train_files_twice = [
    'output_700_epochs_biochem_10times_lowerLR_train_data.txt',
    'output_700_epochs_biochem_SMO_10times_lowerLR_train_data.txt',
    'output_700_epochs_biochem_100times_lowerLR_train_data.txt',
    'output_700_epochs_biochem_SMO_100times_lowerLR_train_data.txt',
    'output_700_epochs_biochem_1000times_lowerLR_train_data.txt',
    'output_700_epochs_biochem_SMO_1000times_lowerLR_train_data.txt',
    'output_original_biochem_SMO_train_data.txt'
]
val_files_twice = [
    'output_700_epochs_biochem_10times_lowerLR_val_data.txt',
    'output_700_epochs_biochem_SMO_10times_lowerLR_val_data.txt',
    'output_700_epochs_biochem_100times_lowerLR_val_data.txt',
    'output_700_epochs_biochem_SMO_100times_lowerLR_val_data.txt',
    'output_700_epochs_biochem_1000times_lowerLR_val_data.txt',
    'output_700_epochs_biochem_SMO_1000times_lowerLR_val_data.txt',
    'output_original_biochem_SMO_val_data.txt'
]

data_train_biochem_twice = {'Model': [], 'Top-1 Train': [], 'Top-3 Train': [], 'Top-5 Train': [], 'Top-10 Train': []}
data_val_biochem_twice = {'Model': [], 'Top-1 Val': [], 'Top-3 Val': [], 'Top-5 Val': [], 'Top-10 Val': []}
data_test_biochem_twice = {'Model': [], 'Top-1 Test': [], 'Top-3 Test': [], 'Top-5 Test': [], 'Top-10 Test': []}

for train_file_twice, val_file_twice, test_file_twice in zip(train_files_twice, val_files_twice, test_files_twice):
    
    if 'SMO_10times_lowerLR' in train_file_twice and val_file_twice and test_file_twice:
        model_name = '700 epochs biochem SMO 10times lowerLR'
    elif 'SMO_100times_lowerLR' in train_file_twice and val_file_twice and test_file_twice:
        model_name = '700 epochs biochem SMO 100times lowerLR'
    elif 'SMO_1000times_lowerLR' in train_file_twice and val_file_twice and test_file_twice:
        model_name = '700 epochs biochem SMO 1000times lowerLR'
    elif '10times_lowerLR' in train_file_twice and val_file_twice and test_file_twice:
        model_name = '700 epochs biochem 10times lowerLR'
    elif '100times_lowerLR' in train_file_twice and val_file_twice and test_file_twice:
        model_name = '700 epochs biochem 100times lowerLR'
    elif '1000times_lowerLR' in train_file_twice and val_file_twice and test_file_twice:
        model_name = '700 epochs biochem 1000times lowerLR'
    else:
        model_name = 'Original Biochem - SMO'
    
    train_values_twice = extract_top_values(train_file_twice)
    val_values_twice = extract_top_values(val_file_twice)
    test_values_twice = extract_top_values(test_file_twice)
    
    data_train_biochem_twice['Model'].append(model_name)
    data_val_biochem_twice['Model'].append(model_name)
    data_test_biochem_twice['Model'].append(model_name)
    
    for key in ['Top-1', 'Top-3', 'Top-5', 'Top-10']:
        data_train_biochem_twice[f'{key} Train'].append(round(train_values_twice[key],3))
        data_val_biochem_twice[f'{key} Val'].append(round(val_values_twice[key],3))
        data_test_biochem_twice[f'{key} Test'].append(round(test_values_twice[key],3))

df_train_twice = pd.DataFrame(data_train_biochem_twice)
df_val_twice = pd.DataFrame(data_val_biochem_twice)
df_test_twice = pd.DataFrame(data_test_biochem_twice)

In [16]:
df_train_twice

,Model,Top-1 Train,Top-3 Train,Top-5 Train,Top-10 Train
0,700 epochs biochem 10times lowerLR,0.600,0.744,0.778,0.811
1,700 epochs biochem SMO 10times lowerLR,0.541,0.693,0.734,0.766
2,700 epochs biochem 100times lowerLR,0.233,0.360,0.433,0.510
3,700 epochs biochem SMO 100times lowerLR,0.236,0.395,0.465,0.542
4,700 epochs biochem 1000times lowerLR,0.069,0.132,0.163,0.221
5,700 epochs biochem SMO 1000times lowerLR,0.066,0.131,0.183,0.240
6,Original Biochem - SMO,0.013,0.032,0.041,0.051

In [17]:
df_val_twice

,Model,Top-1 Val,Top-3 Val,Top-5 Val,Top-10 Val
0,700 epochs biochem 10times lowerLR,0.282,0.417,0.467,0.522
1,700 epochs biochem SMO 10times lowerLR,0.509,0.658,0.696,0.745
2,700 epochs biochem 100times lowerLR,0.175,0.276,0.333,0.417
3,700 epochs biochem SMO 100times lowerLR,0.213,0.373,0.426,0.521
4,700 epochs biochem 1000times lowerLR,0.057,0.123,0.159,0.214
5,700 epochs biochem SMO 1000times lowerLR,0.087,0.167,0.213,0.262
6,Original Biochem - SMO,0.011,0.030,0.046,0.057

In [18]:
df_test_twice

,Model,Top-1 Test,Top-3 Test,Top-5 Test,Top-10 Test
0,700 epochs biochem 10times lowerLR,0.311,0.455,0.491,0.553
1,700 epochs biochem SMO 10times lowerLR,0.521,0.662,0.696,0.711
2,700 epochs biochem 100times lowerLR,0.198,0.304,0.364,0.451
3,700 epochs biochem SMO 100times lowerLR,0.239,0.380,0.453,0.525
4,700 epochs biochem 1000times lowerLR,0.064,0.135,0.178,0.228
5,700 epochs biochem SMO 1000times lowerLR,0.065,0.133,0.160,0.236
6,Original Biochem - SMO,0.030,0.046,0.057,0.061

In [19]:
import pandas as pd
import re

test_files_twice = [ 
    'output_1000_epochs_biochem_10times_lowerLR_test_data.txt',
    'output_1000_epochs_biochem_SMO_10times_lowerLR_test_data.txt',
    'output_1000_epochs_biochem_100times_lowerLR_test_data.txt',
    'output_1000_epochs_biochem_SMO_100times_lowerLR_test_data.txt',
    'output_1000_epochs_biochem_1000times_lowerLR_test_data.txt',
    'output_1000_epochs_biochem_SMO_1000times_lowerLR_test_data.txt',
    'output_original_biochem_SMO_test_data.txt'
]
train_files_twice = [
    'output_1000_epochs_biochem_10times_lowerLR_train_data.txt',
    'output_1000_epochs_biochem_SMO_10times_lowerLR_train_data.txt',
    'output_1000_epochs_biochem_100times_lowerLR_train_data.txt',
    'output_1000_epochs_biochem_SMO_100times_lowerLR_train_data.txt',
    'output_1000_epochs_biochem_1000times_lowerLR_train_data.txt',
    'output_1000_epochs_biochem_SMO_1000times_lowerLR_train_data.txt',
    'output_original_biochem_SMO_train_data.txt'
]
val_files_twice = [
    'output_1000_epochs_biochem_10times_lowerLR_val_data.txt',
    'output_1000_epochs_biochem_SMO_10times_lowerLR_val_data.txt',
    'output_1000_epochs_biochem_100times_lowerLR_val_data.txt',
    'output_1000_epochs_biochem_SMO_100times_lowerLR_val_data.txt',
    'output_1000_epochs_biochem_1000times_lowerLR_val_data.txt',
    'output_1000_epochs_biochem_SMO_1000times_lowerLR_val_data.txt',
    'output_original_biochem_SMO_val_data.txt'
]

data_train_biochem_twice = {'Model': [], 'Top-1 Train': [], 'Top-3 Train': [], 'Top-5 Train': [], 'Top-10 Train': []}
data_val_biochem_twice = {'Model': [], 'Top-1 Val': [], 'Top-3 Val': [], 'Top-5 Val': [], 'Top-10 Val': []}
data_test_biochem_twice = {'Model': [], 'Top-1 Test': [], 'Top-3 Test': [], 'Top-5 Test': [], 'Top-10 Test': []}

for train_file_twice, val_file_twice, test_file_twice in zip(train_files_twice, val_files_twice, test_files_twice):
    
    if 'SMO_10times_lowerLR' in train_file_twice and val_file_twice and test_file_twice:
        model_name = '1000 epochs biochem SMO 10times lowerLR'
    elif 'SMO_100times_lowerLR' in train_file_twice and val_file_twice and test_file_twice:
        model_name = '1000 epochs biochem SMO 100times lowerLR'
    elif 'SMO_1000times_lowerLR' in train_file_twice and val_file_twice and test_file_twice:
        model_name = '1000 epochs biochem SMO 1000times lowerLR'
    elif '10times_lowerLR' in train_file_twice and val_file_twice and test_file_twice:
        model_name = '1000 epochs biochem 10times lowerLR'
    elif '100times_lowerLR' in train_file_twice and val_file_twice and test_file_twice:
        model_name = '1000 epochs biochem 100times lowerLR'
    elif '1000times_lowerLR' in train_file_twice and val_file_twice and test_file_twice:
        model_name = '1000 epochs biochem 1000times lowerLR'
    else:
        model_name = 'Original Biochem - SMO'
    
    train_values_twice = extract_top_values(train_file_twice)
    val_values_twice = extract_top_values(val_file_twice)
    test_values_twice = extract_top_values(test_file_twice)
    
    data_train_biochem_twice['Model'].append(model_name)
    data_val_biochem_twice['Model'].append(model_name)
    data_test_biochem_twice['Model'].append(model_name)
    
    for key in ['Top-1', 'Top-3', 'Top-5', 'Top-10']:
        data_train_biochem_twice[f'{key} Train'].append(round(train_values_twice[key],3))
        data_val_biochem_twice[f'{key} Val'].append(round(val_values_twice[key],3))
        data_test_biochem_twice[f'{key} Test'].append(round(test_values_twice[key],3))

df_train_twice = pd.DataFrame(data_train_biochem_twice)
df_val_twice = pd.DataFrame(data_val_biochem_twice)
df_test_twice = pd.DataFrame(data_test_biochem_twice)

In [20]:
df_train_twice

,Model,Top-1 Train,Top-3 Train,Top-5 Train,Top-10 Train
0,1000 epochs biochem 10times lowerLR,0.673,0.781,0.803,0.826
1,1000 epochs biochem SMO 10times lowerLR,0.603,0.717,0.741,0.769
2,1000 epochs biochem 100times lowerLR,0.272,0.419,0.492,0.573
3,1000 epochs biochem SMO 100times lowerLR,0.278,0.439,0.515,0.596
4,1000 epochs biochem 1000times lowerLR,0.088,0.151,0.190,0.245
5,1000 epochs biochem SMO 1000times lowerLR,0.089,0.173,0.218,0.277
6,Original Biochem - SMO,0.013,0.032,0.041,0.051

In [21]:
df_val_twice

,Model,Top-1 Val,Top-3 Val,Top-5 Val,Top-10 Val
0,1000 epochs biochem 10times lowerLR,0.298,0.415,0.453,0.509
1,1000 epochs biochem SMO 10times lowerLR,0.563,0.669,0.715,0.741
2,1000 epochs biochem 100times lowerLR,0.193,0.313,0.370,0.453
3,1000 epochs biochem SMO 100times lowerLR,0.255,0.399,0.490,0.574
4,1000 epochs biochem 1000times lowerLR,0.082,0.142,0.181,0.238
5,1000 epochs biochem SMO 1000times lowerLR,0.114,0.186,0.247,0.289
6,Original Biochem - SMO,0.011,0.030,0.046,0.057

In [22]:
df_test_twice

,Model,Top-1 Test,Top-3 Test,Top-5 Test,Top-10 Test
0,1000 epochs biochem 10times lowerLR,0.321,0.450,0.492,0.552
1,1000 epochs biochem SMO 10times lowerLR,0.540,0.673,0.711,0.726
2,1000 epochs biochem 100times lowerLR,0.223,0.331,0.389,0.490
3,1000 epochs biochem SMO 100times lowerLR,0.274,0.426,0.498,0.593
4,1000 epochs biochem 1000times lowerLR,0.078,0.161,0.192,0.255
5,1000 epochs biochem SMO 1000times lowerLR,0.080,0.156,0.198,0.266
6,Original Biochem - SMO,0.030,0.046,0.057,0.061